"""Asset generator for DiskLED's "Vintage" analog VU meter skin.

Dev-only tool (not part of the release payload -- see tools/stage-dist.ps1's
copy list, which does not include tools/). Regenerates every image under
assets/vintage/ from scratch; re-run after editing any constant below (tick/
label color, needle geometry, which meters appear in each mode, ...) instead
of hand-editing the PNGs.

Rev 9: switches from "shared needle sprite composited over a background with
color-key transparency" to "needle baked into each meter's own housing,
frame by frame" -- confirmed on real hardware that TransparentBlt's hard
color-key (an exact-match-or-not test) cannot render an anti-aliased needle
edge, which was invisible in every offline preview render but very visible
running on real hardware. Baking means the needle-to-face blend is ordinary
opaque-image AA; the only color-keyed edge left is each housing's own outer
boundary, which is identical across all 64 frames of a given meter (same
low-impact situation as assets/original/Original_Meters.png's round bezel,
which uses the same technique).

Produces (all pixel-exact PNG, no color-management chunks), written to
assets/vintage/:
  - vintage_<meter>.png  : one 64-frame strip per unique meter (CPU/MEM/DSK/
                           NET/SND/SWP/R/W/IN/OUT/SNDL/SNDR), each frame =
                           that meter's full housing (case, ticks, label,
                           screw-or-blank-lamp-slot) with the needle baked in
                           at that frame's angle. CPU/MEM are reused by both
                           the compact and full layout.cfg sections; SND is
                           compact-only (mono) and SNDL/SNDR are full-only
                           (stereo) -- see METERS/COMPACT_CELLS/FULL_CELLS
                           below.
  - vintage_compact_bg.png / vintage_full_bg.png : the underlying canvas for
                           each mode, now just a flat MaskColor fill sized to
                           that mode's total width -- the housings live in
                           the per-meter strips above, not here.
  - vintage_lamp.png     : one 2-frame (off/on) lamp strip, blitted by the
                           engine over a lamp_slot meter's blank spot.

Tray icons are NOT generated here -- since the tray-independence rework,
tray LED art is skin-independent (assets/tray/<color>/, generated by
tools/generate-tray-icons.ps1), not per-skin.
"""
import math
import os
from PIL import Image, ImageDraw, ImageFont, ImageChops

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "vintage")

SS = 4  # supersampling factor for anti-aliasing

# ---- shared geometry (design units, i.e. the final on-screen pixel scale) --
SCALE = 1 / 3

CASE_W = 132 * SCALE
CASE_H = 94 * SCALE
CASE_R = 7 * SCALE            # housing corner radius
PANEL_MARGIN = 6 * SCALE       # housing black visible around the silver/cream panel
PANEL_H_FRAC = 0.83
BORDER_W = max(1.0, 3 * SCALE)  # silver bevel thickness around the cream face
# Meters sit almost flush against each other, like ganged modules in one
# strip, rather than the wide gap rev 2 used between separate dials.
GAP = 2.0
# No top/bottom padding around the housing -- the case fills the cell
# vertically.
TOP_PAD = 0
BOTTOM_PAD = 0
CELL_W = CASE_W + GAP
CELL_H = TOP_PAD + CASE_H + BOTTOM_PAD

# Center label: kept at a fixed, legible size regardless of SCALE.
LABEL_FONT_PX = 7

# Lamp: shares the screw's centered spot in the black strip below the panel.
LAMP_R = 1.0
LAMP_GLOW_RATIO = 1.35
LAMP_GLOW_ALPHA = 90
LAMP_FRAME_D = 6  # final on-screen strip-frame size; must clear 2*R*GLOW_RATIO

NEEDLE_MIN_DEG = -50.0   # value=0 angle
NEEDLE_MAX_DEG = 50.0    # value=1 angle
NEEDLE_FRAMES = 64

# ---- palette -------------------------------------------------------------
CASE_COL = (24, 22, 22)
CASE_EDGE = (58, 55, 55)          # faint plastic highlight on the case rim
SILVER_HI = (232, 232, 232)
SILVER_LO = (150, 150, 155)
CREAM_HI = (240, 232, 208)
CREAM_LO = (223, 212, 176)
INK_COL = (30, 26, 20)  # the dial ink's full-strength color, before fading below
# Ticks and the center label are faded toward the cream face so the needle
# reads more clearly against them; the ink itself isn't used at full
# strength anywhere. Tune INK_FADE (0 = full-strength ink, 1 = invisible).
INK_FADE = 0.35
TICK_COL = tuple(int(INK_COL[i] + (CREAM_HI[i] - INK_COL[i]) * INK_FADE) for i in range(3))
RED_COL = (176, 24, 20)
LABEL_COL = TICK_COL
NEEDLE_COL = (186, 26, 22)
NEEDLE_SHADOW = (96, 10, 10)
SCREW_COL = (70, 68, 68)
LAMP_ON = (255, 96, 24)
LAMP_OFF = (58, 24, 12)
MASK_COLOR = (255, 0, 255)  # color-keyed transparency (window shape + sprites)

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\georgiab.ttf",
    r"C:\Windows\Fonts\georgia.ttf",
    r"C:\Windows\Fonts\arialbd.ttf",
]

_FONT_CACHE = {}


def load_font(size):
    if size in _FONT_CACHE:
        return _FONT_CACHE[size]
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            f = ImageFont.truetype(path, size)
            _FONT_CACHE[size] = f
            return f
    return ImageFont.load_default()


def add_inset_shadow(img, fx0, fy0, fx1, fy1, ss):
    """Shadow along the face's top and left edges (recessed look). The top
    and left falloffs are combined with max() per pixel so they blend into
    each other at the corner instead of one overwriting the other."""
    face_h = fy1 - fy0
    shadow_h = max(1.5 * ss, face_h * 0.32)
    shadow_w = max(1.5 * ss, face_h * 0.38)
    max_alpha = 100
    ov = Image.new("RGBA", img.size, (0, 0, 0, 0))
    put = ov.load()
    y0i, y1i = int(fy0), int(math.ceil(fy1))
    x0i, x1i = int(fx0), int(math.ceil(fx1))
    for y in range(y0i, y1i):
        dy = (y - fy0) / shadow_h
        top_a = max(0.0, 1.0 - dy) if dy < 1.0 else 0.0
        for x in range(x0i, x1i):
            dx = (x - fx0) / shadow_w
            left_a = max(0.0, 1.0 - dx) if dx < 1.0 else 0.0
            a = top_a if top_a > left_a else left_a
            if a <= 0.0:
                continue
            put[x, y] = (0, 0, 0, int(max_alpha * a * a))
    img.alpha_composite(ov)


def flatten_hard_edge(rgba_img, mask_color=MASK_COLOR, threshold=128):
    """Flattens an RGBA image onto mask_color with a hard (non-AA) cutoff at
    the given alpha threshold, instead of alpha-blending translucent edge
    pixels into mask_color. A soft/blended edge there would leave semi-mask-
    colored fringe pixels that TransparentBlt's hard color-key treats as
    opaque (a visible fringe) instead of transparent. Applied only to each
    housing's outer boundary now (constant across all 64 frames of a given
    meter) -- the needle-to-face edge never touches MaskColor any more, since
    it's baked into the same opaque image as the face."""
    r, g, b, a = rgba_img.split()
    hard_a = a.point(lambda v: 255 if v >= threshold else 0)
    out = Image.new("RGB", rgba_img.size, mask_color)
    rgb = Image.merge("RGB", (r, g, b))
    out.paste(rgb, (0, 0), hard_a)
    return out


# Center of the black strip below the panel, relative to a case's own (x0, 0)
# -- shared by the screw (CPU/MEM/SWP/SND) and the lamp (DSK/NET, R/W/IN/OUT),
# which take over the same spot instead of sitting side by side.
LAMP_CENTER_X = CASE_W / 2
LAMP_CENTER_Y = CASE_H * (PANEL_H_FRAC + 1) / 2


def draw_meter_housing(img: Image.Image, x0, y0, label: str, arrow: str, ss: int,
                        lamp_slot: bool = False):
    """x0, y0 already in supersampled coordinates. lamp_slot=True leaves the
    screw/lamp spot blank -- the shipped background never bakes a lamp state,
    since DiskRW/NetActivity (compact) and DiskRead/DiskWrite/NetIn/NetOut
    (full) are separate runtime sprites blitted there over the real on/off
    state. Everything here (case, bevel, ticks, label, screw/lamp slot) is
    identical across a meter's 64 needle-angle frames, so it's drawn once per
    meter and reused -- see draw_needle, which bakes the one part that
    actually changes per frame onto a copy of this image.

    Returns the needle geometry (cx, pivot_y, arc_pivot_y, r_outer, py1)
    draw_needle needs, so it doesn't have to recompute it from x0/y0/ss."""
    draw = ImageDraw.Draw(img)
    case_w, case_h, case_r = CASE_W * ss, CASE_H * ss, CASE_R * ss
    panel_margin, border_w = PANEL_MARGIN * ss, BORDER_W * ss

    # Housing.
    draw.rounded_rectangle([x0, y0, x0 + case_w, y0 + case_h], radius=case_r,
                            fill=CASE_COL + (255,))
    draw.rounded_rectangle([x0 + ss, y0 + ss, x0 + case_w - ss, y0 + case_h - ss],
                            radius=max(0.0, case_r - ss), outline=CASE_EDGE + (255,),
                            width=max(1, ss // 2))

    px0 = x0 + panel_margin
    py0 = y0 + panel_margin
    px1 = x0 + case_w - panel_margin
    py1 = y0 + case_h * PANEL_H_FRAC
    # The needle's true hinge sits at the case's own bottom edge -- hidden
    # behind the bezel (below the screw/lamp strip), like a real meter
    # movement. Only the part of the needle above py1 (the panel's own
    # bottom edge) is ever drawn; see the clipping below.
    pivot_y = y0 + case_h

    # Silver bevel behind the cream face (angle-shaded for a brushed look).
    light_angle = math.radians(-60)
    for y in range(int(py0), int(math.ceil(py1))):
        t = 0.5 + 0.5 * math.cos(math.radians((y - py0) / max(1.0, py1 - py0) * 40) - light_angle)
        row_col = tuple(int(SILVER_LO[i] + (SILVER_HI[i] - SILVER_LO[i]) * t) for i in range(3))
        draw.line([px0, y, px1, y], fill=row_col + (255,))

    # Cream face, inset within the bevel.
    fx0, fy0, fx1, fy1 = px0 + border_w, py0 + border_w, px1 - border_w, py1 - border_w
    for y in range(int(fy0), int(math.ceil(fy1))):
        t = (y - fy0) / max(1.0, fy1 - fy0)
        row_col = tuple(int(CREAM_HI[i] + (CREAM_LO[i] - CREAM_HI[i]) * t) for i in range(3))
        draw.line([fx0, y, fx1, y], fill=row_col + (255,))

    add_inset_shadow(img, fx0, fy0, fx1, fy1, ss)

    # Tick-mark arc: short ticks near a shallow arc whose pivot sits just
    # below the face.
    face_h = fy1 - fy0
    cx = (fx0 + fx1) / 2
    arc_pivot_y = fy1 + face_h * 0.07
    r_outer = face_h * 0.95
    tick_len = face_h * 0.16
    r1 = r_outer - tick_len
    n_ticks = 13
    for i in range(n_ticks):
        t = i / (n_ticks - 1)
        deg = NEEDLE_MIN_DEG + (NEEDLE_MAX_DEG - NEEDLE_MIN_DEG) * t
        rad = math.radians(deg - 90)
        x1t = cx + r1 * math.cos(rad)
        y1t = arc_pivot_y + r1 * math.sin(rad)
        x2t = cx + r_outer * math.cos(rad)
        y2t = arc_pivot_y + r_outer * math.sin(rad)
        hot = t >= 0.78
        col = RED_COL if hot else TICK_COL
        draw.line([x1t, y1t, x2t, y2t], fill=col + (255,), width=ss)

    # Center label (the part this meter shows -- takes the "VU" spot).
    font = load_font(LABEL_FONT_PX * ss)
    bbox = draw.textbbox((0, 0), label, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    gap = 2.0 * ss
    arrow_w = 4.0 * ss if arrow else 0
    total_w = tw + (gap + arrow_w if arrow else 0)
    ink_left = cx - total_w / 2
    center_y = fy0 + face_h * 0.66  # shared vertical center for text ink + arrow
    draw.text((ink_left - bbox[0], center_y - th / 2 - bbox[1]), label, font=font,
              fill=LABEL_COL + (255,))
    if arrow:
        ax = ink_left + tw + gap
        ah = 3.0 * ss
        if arrow == "up":
            pts = [(ax, center_y + ah), (ax + arrow_w, center_y + ah), (ax + arrow_w / 2, center_y - ah)]
        else:
            pts = [(ax, center_y - ah), (ax + arrow_w, center_y - ah), (ax + arrow_w / 2, center_y + ah)]
        draw.polygon(pts, fill=LABEL_COL + (255,))  # same color as text, not red

    # Screw/rivet, centered in the black strip below the panel (independent
    # of the needle's own hinge point below). Skipped for lamp_slot meters,
    # whose runtime lamp sprite covers this exact spot instead (see
    # LAMP_CENTER_X/Y above).
    if not lamp_slot:
        scy = (py1 + (y0 + case_h)) / 2
        scr = max(1.0 * ss, 4 * ss * SCALE)
        draw.ellipse([cx - scr, scy - scr, cx + scr, scy + scr], fill=SCREW_COL + (255,),
                     outline=(20, 18, 18, 255))

    return (cx, pivot_y, arc_pivot_y, r_outer, py1)


def draw_needle(img: Image.Image, geometry, needle_deg, ss: int):
    """Bakes the needle at needle_deg onto img (a copy of a
    draw_meter_housing base image), on top of everything else, matching the
    engine's own draw order of background-then-sprite. Drawn from the true
    hinge at the case's own bottom edge (cx, pivot_y) -- hidden behind the
    bezel below the screw/lamp strip, like a real meter movement -- but
    aimed at the exact point on the tick arc's own circle (cx, arc_pivot_y /
    r_outer) for this angle, so the tip always lands on the scale, including
    at NEEDLE_MIN_DEG/NEEDLE_MAX_DEG where it must meet the first/last tick.
    Only the part of the needle above py1 (the panel's own bottom edge) is
    ever drawn; see the clipping below."""
    cx, pivot_y, arc_pivot_y, r_outer, py1 = geometry
    rad = math.radians(needle_deg - 90)
    tip_x = cx + r_outer * math.cos(rad)
    tip_y = arc_pivot_y + r_outer * math.sin(rad)
    perp = rad + math.pi / 2
    base_w = max(0.6 * ss, 2.0 * SCALE * ss)
    bx, by = base_w * math.cos(perp), base_w * math.sin(perp)
    needle_layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ndraw = ImageDraw.Draw(needle_layer)
    ndraw.polygon([
        (cx - bx, pivot_y - by),
        (cx + bx, pivot_y + by),
        (tip_x, tip_y),
    ], fill=NEEDLE_SHADOW + (255,))
    ndraw.line([cx, pivot_y, tip_x, tip_y], fill=NEEDLE_COL + (255,), width=ss)
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rectangle([0, 0, img.width, py1], fill=255)
    r, g, b, a = needle_layer.split()
    needle_layer = Image.merge("RGBA", (r, g, b, ImageChops.multiply(a, mask)))
    img.alpha_composite(needle_layer)


def draw_lamp(draw: ImageDraw.ImageDraw, cx, cy, r, on: bool):
    col = LAMP_ON if on else LAMP_OFF
    if on:
        glow_r = r * LAMP_GLOW_RATIO
        draw.ellipse([cx - glow_r, cy - glow_r, cx + glow_r, cy + glow_r],
                     fill=(255, 190, 130, LAMP_GLOW_ALPHA))
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=col + (255,), outline=(20, 10, 5, 255))


def build_background(cells, filename):
    """Now just a flat MaskColor canvas sized to this mode's total width --
    every housing lives in its own per-meter strip (build_meter_strip), not
    here."""
    w = int(math.ceil(CELL_W * len(cells) + GAP))
    h = int(math.ceil(CELL_H))
    img = Image.new("RGB", (w, h), MASK_COLOR)
    img.save(os.path.join(OUT, filename))
    print(filename, img.size)


def build_meter_strip(label, arrow, lamp_slot, filename):
    """Bakes this meter's housing + ticks + label + screw-or-blank-lamp-slot
    once, then composites the needle (at each of 64 angles) onto a copy of
    it. The housing is pixel-identical across all 64 frames, so redrawing it
    from scratch per frame -- particularly add_inset_shadow's per-pixel
    Python loop -- would be 64x the work for no visual difference. Returns
    the pre-flatten RGBA frames too, for the full-scene review preview."""
    w, h = int(math.ceil(CASE_W)), int(math.ceil(CASE_H))
    housing = Image.new("RGBA", (w * SS, h * SS), (0, 0, 0, 0))
    geometry = draw_meter_housing(housing, 0, 0, label, arrow, SS, lamp_slot=lamp_slot)

    frames = []
    for f in range(NEEDLE_FRAMES):
        t = f / (NEEDLE_FRAMES - 1)
        deg = NEEDLE_MIN_DEG + (NEEDLE_MAX_DEG - NEEDLE_MIN_DEG) * t
        big = housing.copy()
        draw_needle(big, geometry, deg, SS)
        frames.append(big.resize((w, h), Image.LANCZOS))

    strip = Image.new("RGB", (w, h * NEEDLE_FRAMES), MASK_COLOR)
    for f, frame in enumerate(frames):
        strip.paste(flatten_hard_edge(frame, MASK_COLOR), (0, f * h))
    strip.save(os.path.join(OUT, filename))
    print(filename, strip.size)
    return frames


def build_lamp_strip(filename):
    """Frame size (and lamp radius within it) shares LAMP_R/LAMP_FRAME_D with
    LAMP_CENTER_X/Y above, so the standalone asset and a meter's blank lamp
    slot can't drift out of sync. Hard-cut at MaskColor for the same reason
    as build_meter_strip's housing edge."""
    d = LAMP_FRAME_D
    big = Image.new("RGBA", (d * SS, d * 2 * SS), (0, 0, 0, 0))
    draw = ImageDraw.Draw(big)
    r = LAMP_R * SS
    cx = d / 2 * SS
    for i, on in enumerate((False, True)):
        cy = (i * d + d / 2) * SS
        draw_lamp(draw, cx, cy, r, on)
    strip = big.resize((d, d * 2), Image.LANCZOS)
    flat = flatten_hard_edge(strip, MASK_COLOR)
    flat.save(os.path.join(OUT, filename))
    print(filename, flat.size)


def case_x(index):
    """A meter's case left edge (== its strip sprite's X), design px."""
    return int(round(GAP + index * CELL_W))


def lamp_xy(index):
    """A lamp sprite's destination (X, Y): the strip frame's own lamp center
    (LAMP_FRAME_D/2, LAMP_FRAME_D/2) landing exactly on LAMP_CENTER_X/Y."""
    x = case_x(index) + LAMP_CENTER_X - LAMP_FRAME_D / 2
    y = LAMP_CENTER_Y - LAMP_FRAME_D / 2
    return int(round(x)), int(round(y))


def build_scene_preview(cells, lamp_slots, meter_frames_by_label, values, lamp_states, filename):
    """Composites the real per-meter baked frames (and, for lamp_slot
    meters, the real vintage_lamp.png sprite) onto a blank canvas at their
    layout.cfg positions -- review-only, showing exactly what the shipped
    assets look like once the engine blits them at runtime."""
    w = int(math.ceil(CELL_W * len(cells) + GAP))
    h = int(math.ceil(CELL_H))
    canvas = Image.new("RGBA", (w, h), MASK_COLOR + (255,))
    lamp = Image.open(os.path.join(OUT, "vintage_lamp.png")).convert("RGBA")
    fw, fh = lamp.width, lamp.height // 2
    for i, (label, _arrow) in enumerate(cells):
        frames = meter_frames_by_label[label]
        f = int(round(values[i] * (NEEDLE_FRAMES - 1)))
        canvas.alpha_composite(frames[f], (case_x(i), 0))
        if i in lamp_slots:
            on = lamp_states[i]
            frame = lamp.crop((0, fh if on else 0, fw, (2 if on else 1) * fh))
            x, y = lamp_xy(i)
            canvas.alpha_composite(frame, (x, y))
    canvas.convert("RGB").save(os.path.join(OUT, filename))
    print(filename, canvas.size)


if __name__ == "__main__":
    # (key, display_label, arrow, lamp_slot, filename) -- one entry per unique
    # meter design. `key` is only a lookup name for meter_frames/CELLS below;
    # `display_label` is the text actually baked onto the dial, which is why
    # DiskRead ("R") and the new AudioR meter (key "AudioR", also displayed
    # as "R") can coexist. CPU/MEM look identical in both compact and full,
    # so their files are reused by both layout.cfg sections instead of
    # duplicated. SND is compact-only (mono volume); AudioL/AudioR are
    # full-only (stereo volume) and share SND's design apart from the label.
    METERS = [
        ("CPU", "CPU", "", False, "vintage_cpu.png"),
        ("MEM", "MEM", "", False, "vintage_mem.png"),
        ("DSK", "DSK", "", True, "vintage_dsk.png"),
        ("NET", "NET", "", True, "vintage_net.png"),
        ("SND", "SND", "", False, "vintage_snd.png"),
        ("SWP", "SWP", "", False, "vintage_swp.png"),
        ("R", "R", "down", True, "vintage_r.png"),
        ("W", "W", "up", True, "vintage_w.png"),
        ("IN", "IN", "down", True, "vintage_in.png"),
        ("OUT", "OUT", "up", True, "vintage_out.png"),
        ("AudioL", "L", "", False, "vintage_sndl.png"),
        ("AudioR", "R", "", False, "vintage_sndr.png"),
    ]
    meter_frames = {}
    for key, display, arrow, lamp_slot, filename in METERS:
        meter_frames[key] = build_meter_strip(display, arrow, lamp_slot, filename)

    build_lamp_strip("vintage_lamp.png")

    COMPACT_CELLS = [("CPU", ""), ("MEM", ""), ("DSK", ""), ("NET", ""), ("SND", "")]
    FULL_CELLS = [("CPU", ""), ("MEM", ""), ("SWP", ""), ("R", "down"), ("W", "up"),
                  ("IN", "down"), ("OUT", "up"), ("AudioL", ""), ("AudioR", "")]
    COMPACT_LAMP_SLOTS = {2, 3}          # DSK, NET
    FULL_LAMP_SLOTS = {3, 4, 5, 6}       # R, W, IN, OUT

    build_background(COMPACT_CELLS, "vintage_compact_bg.png")
    build_background(FULL_CELLS, "vintage_full_bg.png")

    # layout.cfg coordinates -- printed here (not hand-derived) so the values
    # written into assets/vintage/layout.cfg can't drift from what these
    # assets actually assume.
    print("\n-- layout.cfg positions (design px) --")
    print("meter strip frame size: %dx%d, Frames=%d" %
          (int(math.ceil(CASE_W)), int(math.ceil(CASE_H)), NEEDLE_FRAMES))
    print("lamp strip:   File=vintage_lamp.png Frames=2, frame size %dx%d" %
          (LAMP_FRAME_D, LAMP_FRAME_D))
    for mode, cells, lamp_slots in (("compact", COMPACT_CELLS, COMPACT_LAMP_SLOTS),
                                     ("full", FULL_CELLS, FULL_LAMP_SLOTS)):
        for i, (name, _arrow) in enumerate(cells):
            lx, ly = lamp_xy(i) if i in lamp_slots else (None, None)
            print("  %-8s[%d] %-4s X=%d Y=0%s" % (
                mode, i, name, case_x(i),
                "  lamp X=%d Y=%d" % (lx, ly) if lx is not None else ""))

    # Full-scene review previews (needle values + lamp on/off are arbitrary
    # demo values, not meaningful data).
    compact_lamp_demo = {2: False, 3: True}          # DSK=off, NET=on
    full_lamp_demo = {3: False, 4: True, 5: False, 6: True}  # R=off,W=on,IN=off,OUT=on
    build_scene_preview(COMPACT_CELLS, COMPACT_LAMP_SLOTS, meter_frames,
                         [0.12, 0.38, 0.62, 0.85, 0.5], compact_lamp_demo, "preview_compact.png")
    build_scene_preview(FULL_CELLS, FULL_LAMP_SLOTS, meter_frames,
                         [0.15, 0.4, 0.55, 0.3, 0.7, 0.2, 0.85, 0.3, 0.6], full_lamp_demo, "preview_full.png")
